import { actiwebToCheckpoint, checkpointToActiweb } from './actiweb.mapper';

describe('actiweb.mapper', () => {
  beforeEach(() => {
    const g: any = globalThis as any;
    if (!g.crypto) {
      g.crypto = {};
    }

    spyOn(g.crypto, 'randomUUID').and.returnValue('uuid-test-1');
  });

  it('should map form values to checkpoint payload', () => {
    const result = actiwebToCheckpoint({
      structuralStrategies: true,
      range7mxn: true,
      tiie196mxn: false,
      range196mxn: true,
      range7eu: true,
      range7usd: false,
      dnt7usd: true,
      clientSic: true,
      clientActions: false,
      clientMargin: true,
      clientPlan: false,
      planType: 'PENSION',
      clientFc: true,
      clientInvestment: false,
      accountStatement: true,
      liquidatingAccount: false,
      employeeContract: true,
      creditContract: false,
      creditType: 'REVOLVENTE',
      rmmOps: true,
      rdw: false,
      restrictTransfers: true,
      minimumMarketability: true,
      mmClass: 'CLASE_A',
      highSpeedChannel: 'CANAL_1',
      noMarketingRequired: true,
      stabContracts: false,
      sophisticatedClient: true,
      alphaInvestment: false,
      allConfirmations: true,
      treasuryOperations: false,
      capitalDeskTrading: true,
      moneyDeskTrading: false,
      invFundsTrading: true,
      portfolioAdmin: true,
      portfolioSafeType: 'SAFE',
      contractOriginBank: 'BANCO',
      alphaInv: true,
      alphaInvPortType: 'PORT-1',
      alphaInvPromo: 'PROMO-1',
      estacm: true,
      pwmContract: false,
      pwmPortfolio: 'PORT-PWM',
      pwmPromo: 'PROMO-PWM',
      assetManagement: true,
      futEligCapDesk: true,
      activationDate: '13/05/2026',
      activationUserCode: 'USR-A',
      activationUserName: 'Usuario Alta',
      deactivationDate: '01/06/2026',
      deactivationUserCode: 'USR-B',
      deactivationUserName: 'Usuario Baja',
      minPortException: true,
      highVelocityTrading: false,
      distributedClosed: 'KEY-1',
      repoAgreementFunds: true,
      derivativeContracts: false,
      extRepoOpsPart: true,
      facOpsPart: false,
      warrantOperations: true,
      shortSalesManagement: false,
      globalBdPart: true,
      purchPowerPos: false,
      operateWithWarrant: true,
      shortSalesMgmtAlt: false,
      routeEligCapDesk: true,
      validityDate: '2026-07-01',
    } as any);

    expect(result).toEqual({
      structuredNotes: {
        structuredNotesStrategiesCp: true,
        accumulateRangeNoteMxn7Days: true,
        tiieNoteMxn196Days: false,
        accumulatedRangeNoteMxn196Days: true,
        europeanRangenoteUsd7Days: true,
        accumulatedRangeNoteUsd7Days: false,
        dntNoteUsd7Days: true,
      },
      client: {
        clientOperatesSic: true,
        clientOperatesStocks: false,
        clientHasMarginOperation: true,
        clientHasRetirementPlan: false,
        retirementPlanType: 'PENSION',
        clientHasTrust: true,
        lenderInvestmentFunds: false,
      },
      generalFeatures: {
        printAccountStatement: true,
        settlementAccount: false,
        employeeContract: true,
        contractUsedForCredit: false,
        creditType: 'REVOLVENTE',
        restrictMoneyMarketOperations: true,
        restrictDespositWithdrawals: false,
        restrictTransfers: true,
        minimumMarketability: true,
        minimumMarketabilityClassification: 'CLASE_A',
        highSpeedChannel: 'CANAL_1',
        noMarketingRequired: true,
        stabilizationContracts: false,
        indicateSphisticatedClient: true,
        alphaInvestmentNumber: false,
      },
      confirmations: {
        selectAllConfirmations: true,
        treasuryDepositsWithdrawals: false,
        capitalMarketsTrading: true,
        moneyMarketsTrading: false,
        investmentFundsTrading: true,
      },
      portfolio: {
        portfolioManagementFee: true,
        portfolioManagementFeeType: 'SAFE',
        contractOriginIsBank: 'BANCO',
        alphaInvestment: true,
        alphaInvestmentPortfolio: 'PORT-1',
        alphaInvestmentPromoter: 'PROMO-1',
        estam: true,
        privateWealthManagementContract: false,
        privateWealthManagementPortfolio: 'PORT-PWM',
        privateWealthManagementPromoter: 'PROMO-PWM',
        assetManagement: true,
      },
      stockExchangeCapital: {
        capitalMarketsRoutingEligibility: true,
        activationDate: '13/05/2026',
        activationUserCode: 'USR-A',
        activationUserName: 'Usuario Alta',
        deactivationDate: '01/06/2026',
        deactivationUserCode: 'USR-B',
        deactivationUserName: 'Usuario Baja',
        minimumPortfolioException: true,
        operatesHighSpeedChannel: false,
        qualifiedInvestorKey: 'KEY-1',
        repurchaseFundsContracts: true,
        omnibusContract: false,
        acceptAutoEntryOperations: true,
        acceptFacilitationOperations: false,
        operatesWarrant: true,
        shortSales: false,
        participatesGlobalBreakdown: true,
        operatesWithoutPurchasePowerPosition: false,
      },
      bankCapitals: {
        operatesWarrant: true,
        shortSales: false,
        capitalMarketsRoutingEligibility: true,
        validityDate: '01/07/2026',
      },
    });
  });

  it('should map checkpoint data back to form values', () => {
    const result = checkpointToActiweb({
      structuredNotes: {
        structuredNotesStrategiesCp: true,
        accumulateRangeNoteMxn7Days: false,
        tiieNoteMxn196Days: true,
        accumulatedRangeNoteMxn196Days: false,
        europeanRangenoteUsd7Days: true,
        accumulatedRangeNoteUsd7Days: false,
        dntNoteUsd7Days: true,
      },
      client: {
        clientOperatesSic: true,
        clientOperatesStocks: false,
        clientHasMarginOperation: true,
        clientHasRetirementPlan: false,
        retirementPlanType: 'PENSION',
        clientHasTrust: true,
        lenderInvestmentFunds: false,
      },
      generalFeatures: {
        printAccountStatement: true,
        settlementAccount: false,
        employeeContract: true,
        contractUsedForCredit: false,
        creditType: 'REVOLVENTE',
        restrictMoneyMarketOperations: true,
        restrictDespositWithdrawals: false,
        restrictTransfers: true,
        minimumMarketability: true,
        minimumMarketabilityClassification: 'CLASE_A',
        highSpeedChannel: 'CANAL_1',
        noMarketingRequired: true,
        stabilizationContracts: false,
        indicateSphisticatedClient: true,
        alphaInvestmentNumber: false,
      },
      confirmations: {
        selectAllConfirmations: true,
        treasuryDepositsWithdrawals: false,
        capitalMarketsTrading: true,
        moneyMarketsTrading: false,
        investmentFundsTrading: true,
      },
      portfolio: {
        portfolioManagementFee: true,
        portfolioManagementFeeType: 'SAFE',
        contractOriginIsBank: 'Si',
        alphaInvestment: true,
        alphaInvestmentPortfolio: 'PORT-1',
        alphaInvestmentPromoter: 'PROMO-1',
        estam: true,
        privateWealthManagementContract: false,
        privateWealthManagementPortfolio: 'PORT-PWM',
        privateWealthManagementPromoter: 'PROMO-PWM',
        assetManagement: true,
      },
      stockExchangeCapital: {
        capitalMarketsRoutingEligibility: true,
        activationDate: '13/05/2026',
        activationUserCode: 'USR-A',
        activationUserName: 'Usuario Alta',
        deactivationDate: '01/06/2026',
        deactivationUserCode: 'USR-B',
        deactivationUserName: 'Usuario Baja',
        minimumPortfolioException: true,
        operatesHighSpeedChannel: false,
        qualifiedInvestorKey: 'KEY-1',
        repurchaseFundsContracts: true,
        omnibusContract: false,
        acceptAutoEntryOperations: true,
        acceptFacilitationOperations: false,
        operatesWarrant: true,
        shortSales: false,
        participatesGlobalBreakdown: true,
        operatesWithoutPurchasePowerPosition: false,
      },
      bankCapitals: {
        operatesWarrant: true,
        shortSales: false,
        capitalMarketsRoutingEligibility: true,
        validityDate: '01/07/2026',
      },
    } as any);

    expect(result).toEqual({
      structuralStrategies: true,
      range7mxn: false,
      tiie196mxn: true,
      range196mxn: false,
      range7eu: true,
      range7usd: false,
      dnt7usd: true,
      clientSic: true,
      clientActions: false,
      clientMargin: true,
      clientPlan: false,
      planType: 'PENSION',
      clientFc: true,
      clientInvestment: false,
      accountStatement: true,
      liquidatingAccount: false,
      employeeContract: true,
      creditContract: false,
      creditType: 'REVOLVENTE',
      rmmOps: true,
      rdw: false,
      restrictTransfers: true,
      minimumMarketability: true,
      mmClass: 'CLASE_A',
      highSpeedChannel: 'CANAL_1',
      noMarketingRequired: true,
      stabContracts: false,
      sophisticatedClient: true,
      alphaInvestment: false,
      allConfirmations: true,
      treasuryOperations: false,
      capitalDeskTrading: true,
      moneyDeskTrading: false,
      invFundsTrading: true,
      portfolioAdmin: true,
      portfolioSafeType: 'SAFE',
      contractOriginBank: 'Si',
      alphaInv: true,
      alphaInvPromo: 'PROMO-1',
      estacm: true,
      pwmContract: false,
      pwmPortfolio: 'PORT-PWM',
      pwmPromo: 'PROMO-PWM',
      assetManagement: true,
      alphaInvPortType: 'PORT-1',
      futEligCapDesk: true,
      activationDate: '13/05/2026',
      activationUserCode: 'USR-A',
      activationUserName: 'Usuario Alta',
      deactivationDate: '01/06/2026',
      deactivationUserCode: 'USR-B',
      deactivationUserName: 'Usuario Baja',
      minPortException: true,
      highVelocityTrading: false,
      distributedClosed: 'KEY-1',
      derivativeContracts: false,
      extRepoOpsPart: true,
      facOpsPart: false,
      warrantOperations: true,
      shortSalesManagement: false,
      globalBdPart: true,
      purchPowerPos: false,
      repoAgreementFunds: true,
      operateWithWarrant: true,
      shortSalesMgmtAlt: false,
      routeEligCapDesk: true,
      validityDate: '2026-07-01',
    });
  });

  it('should fallback to defaults when form values are missing', () => {
    const result = actiwebToCheckpoint({} as any);

    expect(result.structuredNotes).toEqual({
      structuredNotesStrategiesCp: false,
      accumulateRangeNoteMxn7Days: false,
      tiieNoteMxn196Days: false,
      accumulatedRangeNoteMxn196Days: false,
      europeanRangenoteUsd7Days: false,
      accumulatedRangeNoteUsd7Days: false,
      dntNoteUsd7Days: false,
    });
    expect(result.client).toEqual({
      clientOperatesSic: false,
      clientOperatesStocks: false,
      clientHasMarginOperation: false,
      clientHasRetirementPlan: false,
      retirementPlanType: '',
      clientHasTrust: false,
      lenderInvestmentFunds: false,
    });
    expect(result.generalFeatures.minimumMarketability).toBeUndefined();
    expect(result.portfolio.contractOriginIsBank).toBeUndefined();
    expect(result.stockExchangeCapital.operatesWarrant).toBeUndefined();
    expect(result.bankCapitals).toEqual({
      operatesWarrant: false,
      shortSales: false,
      capitalMarketsRoutingEligibility: false,
      validityDate: '',
    });
  });
});