import { EnvFile } from "../app/shared/models/environment";

const host_mock = 'https://private-e8385-enipsrevnitca.apiary-mock.com';
const HOST_ACTINVER = 'https://apicloud-qa.actinver.com.mx';
const HOST_ACTINVER_USR_LOGIN = 'https://qa-api.actinver.com.mx';

export const environment: EnvFile = {
  production: true,
  name: 'qa',
  applicationId: '2f34a20b-5a96-4778-a9b4-aaf918f1dd94',
  allowLog: true,
  api: {
    host: 'qa',
    catalogs: {
      accountDocumentKit        : HOST_ACTINVER + '/cross/catalogs/account-document-kit',
      accountStatement          : HOST_ACTINVER + '/cross/catalogs/account-statement',
      accountRole               : HOST_ACTINVER + '/cross/catalogs/account-rol',
      accountType               : HOST_ACTINVER + '/cross/catalogs/account-type',
      addressRole               : HOST_ACTINVER + '/cross/catalogs/address-rol',
      addressType               : HOST_ACTINVER + '/cross/catalogs/address-type',
      advisor                   : HOST_ACTINVER + '/cross/catalogs/advisor',
      amountRetreatsAvg         : HOST_ACTINVER + '/cross/catalogs/average/amount/retreats',
      authorizedPerson          : HOST_ACTINVER + '/cross/catalogs/authorized-person',
      bank                      : HOST_ACTINVER + '/cross/catalogs/banks',
      branch                    : host_mock + '/cross/catalogs/branches',
      cfdi                      : HOST_ACTINVER + '/cross/catalogs/cfdi',
      classificationPerson      : HOST_ACTINVER + '/cross/catalogs/person-type',
      clientKnowledge           : HOST_ACTINVER + '/cross/catalogs/client-knowledge',
      clientNoGuaranteedIpab    : HOST_ACTINVER + '/cross/catalogs/client-no-guaranteed-ipab',
      contract                  : HOST_ACTINVER + '/cross/catalogs/contracts',
      contractTop               : HOST_ACTINVER + '/cross/catalogs/contracts/search',
      country                   : HOST_ACTINVER + '/cross/catalogs/countries',
      currencyType              : HOST_ACTINVER + '/cross/catalogs/currency-type',
      districtMunicipality      : HOST_ACTINVER + '/cross/catalogs/district-municipality',
      documentType              : HOST_ACTINVER + '/cross/catalogs/document-type',
      economicActivity          : HOST_ACTINVER + '/cross/catalogs/economic-activity',
      economicActivityAccredited: HOST_ACTINVER + '/cross/catalogs/economic-activity-accredited',
      economicSector            : HOST_ACTINVER + '/cross/catalogs/economic-sector',
      experienceTime            : HOST_ACTINVER + '/cross/catalogs/experience-time',
      federalEntity             : HOST_ACTINVER + '/cross/catalogs/federal-entity',
      financialCenter           : HOST_ACTINVER + '/cross/catalogs/financial-center',
      fiscalCertificate         : HOST_ACTINVER + '/cross/catalogs/fiscal-certificate',
      fiscalRegime              : HOST_ACTINVER + '/cross/catalogs/fiscal-regime',
      fiscalPersonType          : HOST_ACTINVER + '/cross/catalogs/fiscal-person-type',
      fiscalPersonSubType       : HOST_ACTINVER + '/cross/catalogs/fiscal-person-subtype',
      fundsOriginCategory       : HOST_ACTINVER + '/cross/catalogs/funds-origin-category',
      identificationType        : HOST_ACTINVER + '/cross/catalogs/identification-type',
      internationalBanks        : HOST_ACTINVER + '/cross/catalogs/banks',
      interviewPlace            : HOST_ACTINVER + '/cross/catalogs/interview-place',
      investmentType            : HOST_ACTINVER + '/cross/catalogs/investment-type',
      maritalStatus             : HOST_ACTINVER + '/cross/catalogs/marital-status',
      marriageType              : HOST_ACTINVER + '/cross/catalogs/marriage-type',
      monthlyDeposit            : HOST_ACTINVER + '/cross/catalogs/monthly-operationals-number',
      monthlyDepositAvg         : HOST_ACTINVER + '/cross/catalogs/monthly-operationals-amount',
      nationality               : HOST_ACTINVER + '/cross/catalogs/nationalities',
      occupations               : HOST_ACTINVER + '/cross/catalogs/occupations',
      origin_resource           : HOST_ACTINVER + '/cross/catalogs/origin/resources',
      paymentPeriod             : HOST_ACTINVER + '/cross/catalogs/payment-period',
      personRole                : HOST_ACTINVER + '/cross/catalogs/person-rol',
      personType                : HOST_ACTINVER + '',
      phoneType                 : HOST_ACTINVER + '/cross/catalogs/telephone-type',
      profileInvestment         : HOST_ACTINVER + '/cross/catalogs/profile-investment',
      proofOfAddressType        : HOST_ACTINVER + '/cross/catalogs/proof-of-address-type',
      propertyType              : HOST_ACTINVER + '/cross/catalogs/property-type',
      relationships             : HOST_ACTINVER + '/cross/catalogs/relationships',
      residentialArea           : HOST_ACTINVER + '/cross/catalogs/residential-area',
      riskGroup                 : HOST_ACTINVER + '/cross/catalogs/risk-group',
      sector                    : HOST_ACTINVER + '/cross/catalogs/sector',
      serviceSubtype            : HOST_ACTINVER + '/cross/catalogs/service-subtype',
      serviceType               : HOST_ACTINVER + '/cross/catalogs/service-type',
      signatureType             : HOST_ACTINVER + '/cross/catalogs/signature-type',
      taxId                     : HOST_ACTINVER + '/cross/catalogs/tax-id',
      transactionalLimits       : HOST_ACTINVER + '/cross/catalogs/transactional-limit',
      startedWorking            : HOST_ACTINVER + '/cross/catalogs/started-working',
      subcontract               : HOST_ACTINVER + '/cross/catalogs/contracts/sub-contracts',
      subsidiaries              : host_mock + '/cross/catalogs/subsidiaries',
      strategiesEquity          : HOST_ACTINVER + '/cross/catalogs/strategies-equity',
    },
    services: {
      otcSendSms            : HOST_ACTINVER + '/cross/security/otc/sendSms',
      otcSendEmail          : HOST_ACTINVER + '/cross/security/otc/sendEmail',
      otcValidate           : HOST_ACTINVER + '/cross/security/otc/validate',
      saveCheckpoint        : HOST_ACTINVER + '/person/onboarding/prospects/checkpoint',
      saveCheckpointMant    : HOST_ACTINVER + '/customers/checkpoint',
      saveCheckpointNonContract: HOST_ACTINVER + '/customers/checkpoint/nonContract',
      getCheckpoints        : HOST_ACTINVER + '/person/onboarding/prospects/checkpoints',
      getCheckpointsMant    : HOST_ACTINVER + '/customers/checkpoint/search',
      getCheckpointsCustomer: HOST_ACTINVER + '/customers/search/detail',
      fielValidation        : HOST_ACTINVER + '/person/onboarding/validation/fiel',
      curpValidate          : HOST_ACTINVER + '/cross/kyc/validation/curp',
      notifications         : HOST_ACTINVER + '/customers/contact-data-notification'
    },
    salesPractices: {
      getQuiz                  : HOST_ACTINVER + '/customers/sales-practice/quiz',
      getQuizRate              : HOST_ACTINVER + '/customers/sales-practice/quiz/rate',
      getQuizReprofilingUrl    : HOST_ACTINVER + '/customers/salespractices/re-profiling/quiz',
      getQuizRateReprofilingUrl: HOST_ACTINVER + '/customers/salespractices/re-profiling/quiz/rate',
      getQuizRateConfirm       : HOST_ACTINVER + '/customers/salespractices/re-profiling/quiz/rate/confirm',
      getProfilingDocument     : HOST_ACTINVER + '/customers/sales-practice/profiling-document',
      generateWfReprofile      : HOST_ACTINVER + '/customers/workflow/registerDetail',
    },
    fiel             : HOST_ACTINVER + '/person/onboarding/validation/fiel',
    homonyms         : HOST_ACTINVER + '/person/onboarding/validation/homonyms',
    searchCustomer   : HOST_ACTINVER + '/customers/search',
    searchApplication: HOST_ACTINVER + '/customers/search/applications/bypersonaldata',
    watchlist        : HOST_ACTINVER + '/cross/kyc/validation/watchlist',
    zipCode          : HOST_ACTINVER + '/cross/catalogs/zip-code',
    assignmentDetail : HOST_ACTINVER + '/customers/workflow/assignment-detail',
    take             : HOST_ACTINVER + '/customers/workflow/take',
    updateStatus     : HOST_ACTINVER + '/customers/workflow/update-status',
    detail           : HOST_ACTINVER + '/customers/workflow/detail',
    detailPld        : HOST_ACTINVER + '/customers/workflow/pld-detail',
    detailCurpAndrfc : HOST_ACTINVER + '/customers/workflow/query/identification',
    approvalHomoPf   : HOST_ACTINVER + '/customers/workflow/unification',
    unificationList  : HOST_ACTINVER + '/customers/workflow/unification-list',
    createWfHomoPf   : HOST_ACTINVER + '/customers/workflow/unification-detail',
    identification   : HOST_ACTINVER + '/customers/workflow/update/identification',
    security: {
      accessToken: HOST_ACTINVER + '/oauth/accesstoken',
      userLogin  : HOST_ACTINVER_USR_LOGIN + '/cross/security/users/login',
      userRoles  : HOST_ACTINVER_USR_LOGIN + '/employees/advisor',
    },
    registerOnboarding: HOST_ACTINVER + '/person/onboarding/register',
    openText          : 'https://digitalizacontratos-qa.actinver.com.mx/digitalizacontratos',
    rePrintContracts  : HOST_ACTINVER + '/customers/reprint/contracts',
    maintenance: {
      spineCatalogRetrieve    : `${HOST_ACTINVER}/cross/catalogs/spine/retrieve`,
      spineCatalogUpsert      : `${HOST_ACTINVER}/cross/catalogs/spine/upsert`,
      replicateContract       : `${HOST_ACTINVER}/customers/replicate/contracts`,
      searchContractByCustomer: `${HOST_ACTINVER}/customers/search/contracts/bycustomer`,
      searchContractByNumber  : `${HOST_ACTINVER}/customers/search/contracts/bynumber`,
      updateStatus            : `${HOST_ACTINVER}/customers/update-status`,
      updateStatusHistory     : `${HOST_ACTINVER}/customers/contract/history`,
      equityRegister          : `${HOST_ACTINVER}/person/onboarding/equity/register`,
      contractsAdvisor        : `${HOST_ACTINVER}/customers/advisor/contracts`,
      transferContracts       : `${HOST_ACTINVER}/customers/transferContracts`,
      replicateCustomer       : `${HOST_ACTINVER}/customers/replicate/customers`,
    },
  },
  otcConfig: {
    disableOtcMail: true,
    disableOtcSms: true,
  },
  dynatrace : 'https://dok.js-cdn.dynatrace.com/jstag/17fd4b29df0/bf44965qfx/17d96fd4e2abba8e_complete.js',
  msalConfig: {
    auth: {
      clientId   : '2f34a20b-5a96-4778-a9b4-aaf918f1dd94',
      authority  : 'https://login.microsoftonline.com/22960abb-bd2b-4f35-a434-4c921455bc49/v2.0',
      redirectUri: 'https://spine-app-926989573047.us-central1.run.app'
    }
  },
  apiConfig: {
    scopes: ['user.read'],
    uri   : 'https://graph.microsoft.com/v1.0/me'
  }
};
