import { GeneralInfoSection } from '../../models/checkpoints/general-info-checkpoint';
import { mapGeneralInfoInit } from './utils-mapper';

describe('Map General Infor Init', () => {

    const inputData: GeneralInfoSection = {
        personClassification: 'aaa',
        economicActivity: 'aaa',
        maritalStatus: 'aaa',
        marriageType: 'aaa',
        sector: 'aaa',
        actinverEmployee: false,
        employeeNumber: 'aaa',
        occupation: 'aaa',
        profession: 'aaa',
        companyName: 'aaa',
        jobTitle: 'aaa',
        companyPhone: 'aaa',
        domicilieType: 'aaa',
        country: 'aaa',
        postalCode: 'aaa',
        federalEntity: 'aaa',
        federalEntityID: 'aaa',
        city: 'aaa',
        cityID: 'aaa',
        municipality: 'aaa',
        municipalityID: 'aaa',
        colony: 'aaa',
        street: 'aaa',
        externalNumber: 'aaa',
        internalNumber: 'aaa',
        website: 'aaa',
        related: false,
        relationship: 'aaa',
        institutionName: 'aaa',
        fiel: 'aaa',
        fielExpirationDate: '10/11/1987',
        operatesChanges: false,
        banxicoAuthorization: 'aaa',
        nonGuaranteedByIPAB: 'aaa',
        acting: false,
        hasSupplier: false,
        mensajesMt940: false,
        codigoSwiftBic: 'aaa',
        isEquity: false,
    }

    const expectedResult = {
        personClassification: 'aaa',
        economicActivity: 'aaa',
        maritalStatus: 'aaa',
        marriageType: 'aaa',
        sector: 'aaa',
        actinverEmployee: false,
        employeeNumber: 'aaa',
        occupation: 'aaa',
        profession: 'aaa',
        companyName: 'aaa',
        jobTitle: 'aaa',
        companyPhone: 'aaa',
        country: 'aaa',
        street: 'aaa',
        externalNumber: 'aaa',
        internalNumber: 'aaa',
        postalCode: 'aaa',
        federalEntity: 'aaa',
        city: 'aaa',
        municipality: 'aaa',
        website: 'aaa',
        related: false,
        relationship: 'aaa',
        institutionName: 'aaa',
        fiel: 'aaa',
        fielExpirationDate: '10/11/1987',
        banxicoAuthorization: true,
        nonGuaranteedByIPAB: 'aaa',
        acting: false,
        hasSupplier: false ,
        operatesChanges: false,
        addressType: 'aaa',
        neighborhood: 'aaa',
    }

    it('should return OK object', () => {
        const result = mapGeneralInfoInit(inputData);
        expect(result).toEqual(expectedResult);
    });

    it('should return DEFAULT object', () => {
        const result = mapGeneralInfoInit(null);

        const expectedObject = {
            personClassification: '',
            economicActivity: '',
            maritalStatus: '',
            marriageType: '',
            sector: '',
            actinverEmployee: false,
            employeeNumber: '',
            occupation: '',
            profession: '',
            companyName: '',
            jobTitle: '',
            companyPhone: '',
            country: '',
            street: '',
            externalNumber: '',
            internalNumber: '',
            postalCode: '',
            federalEntity: '',
            city: '',
            municipality: '',
            website: '',
            related: false,
            relationship: '',
            institutionName: '',
            fiel: '',
            fielExpirationDate: '',
            banxicoAuthorization: true,
            nonGuaranteedByIPAB: '',
            acting: false,
            hasSupplier: false ,
            operatesChanges: true,
            addressType: '',
            neighborhood: '',
        };
        expect(result).toEqual(expectedObject);
    });
});
