import {
  checkpointMantToGeneralInfo,
  generalInfoToCheckpointMant,
} from './general-info-mant-mapper';
import { GeneralInfoSection } from '../../../models/checkpoints/general-info-checkpoint';
import { GeneralInfoContract } from '../../../models/general-info';

describe('general-info-mant-mapper', () => {
  describe('generalInfoToCheckpointMant', () => {
    it('debe mapear la seccion y el contrato a checkpoint para direccion en MX', () => {
      const request: GeneralInfoSection = {
        personClassification: 'A',
        economicActivity: 'ACT-01',
        maritalStatus: '1',
        marriageType: 'SOCIEDAD',
        sector: 'FINANZAS',
        actinverEmployee: true,
        employeeNumber: 'EMP001',
        occupation: 'ANALISTA',
        profession: 'CONTADOR',
        companyName: 'ACTINVER',
        jobTitle: 'GERENTE',
        companyPhone: '5555555555',
        domicilieType: 'CASA',
        country: 'MX',
        postalCode: '01000',
        federalEntity: 'CIUDAD DE MEXICO',
        federalEntityID: '09',
        city: 'ALVARO OBREGON',
        cityID: '001',
        municipality: 'ALVARO OBREGON',
        municipalityID: '010',
        colony: 'FLORIDA',
        street: 'INSURGENTES',
        externalNumber: '100',
        internalNumber: '2',
        website: 'https://actinver.com',
        related: false,
        relationship: '99',
        institutionName: 'NO APLICA',
        fiel: 'ABC',
        fielExpirationDate: '2026-05-15',
        operatesChanges: true,
        banxicoAuthorization: 'SI',
        nonGuaranteedByIPAB: 'NO',
        acting: true,
        hasSupplier: false,
        mensajesMt940: true,
        codigoSwiftBic: 'ABCDMXMM',
      };

      const contract: GeneralInfoContract = {
        id: 10,
        personId: 20,
        addressId: 30,
        workDataId: 40,
        clientId: 50,
        accountRoleId: 60,
        clientStatus: 'ACTIVE',
        contractStatus: 'OPEN',
        openDate: '2024-01-01',
        initialRiskId: 1,
        initialRiskDescription: 'LOW',
        modifyRiskId: 2,
        modifyRiskDespcription: 'MEDIUM',
        origin: 'WEB',
        n4UpdateDate: '2024-02-01',
        isNumbered: true,
        checkProtected: true,
        isOwnPosition: false,
        isSocialPrevision: true,
        authorizationConsultCreditReports: true,
        biometricsAccount: false,
        facialBiometrics: true,
        enrollmentStatus: 'ENROLLED',
        asociatedDirector: 'DIR01',
        directPromote: 'PROM01',
        financailCenter: 'CENTRO',
        isrPercentage: 10,
        isrMonthlyCommision: 1.5,
        comissionPercentage: 2.5,
        isPMSorety: false,
        isBrokerageHouse: true,
        accountManagementId: 70,
        externalCustody: true,
        custody: 'CUST',
        custodyIndeval: 'INDEVAL',
        financialCenterDelivery: 'FC',
        contractManagement: 'CM',
        gestionType: 'TIPO',
        vip: true,
        strategyTypes: [],
        equityStrategies: ['EQ1'],
        isEquity: true,
        generalInformationId: 80,
        operationReason: 'INVERSION',
        otherReasons: 'NINGUNA',
        operationConfiramtionMedia: 'MAIL',
        documents: true,
        transfers: false,
        accountDeposit: true,
        other: false,
        otherPreferedProduct: 'PROD',
        associateDirectorId: 90,
        asociatedDirectorStatus: 'ACTIVO',
        asociatedDirectorFolio: 'FOL-1',
        asociatedDirectorNumber: 123,
        asociatedDirectorName: 'DIR NOMBRE',
        geolocationId: 100,
        consentGeolocalization: true,
        date: '2024-03-01',
        time: '10:00',
        latitude: '19.4326',
        longitude: '-99.1332',
        incapacity: false,
        incapacityLetter: false,
        dateOfDefunction: '',
        codigoSwiftBic: 'OLDCODE',
        mensajesMt940: false,
      };

      const result = generalInfoToCheckpointMant(request, contract, { executors: [], executorsTable: [], showExecutors: false });

      expect(result.federalEntity).toBe('09');
      expect(result.city).toBe('001');
      expect(result.municipality).toBe('010');
      expect(result.relationship).toBe('');
      expect(result.institutionName).toBe('');
      expect(result.fielExpirationDate).toBe('15/05/2026');
      expect(result.codigoSwiftBic).toBe('ABCDMXMM');
      expect(result.mensajesMt940).toBeTrue();
      expect(result.accountManagement.equityStrategies).toEqual(['EQ1']);
      expect(result.generalInformation.referringProduct.depositInAccount).toBeTrue();
      expect(result.personId).toBe(20);
      expect(result.isEquity).toBeTrue();
    });

    it('debe conservar ubicacion textual para pais distinto de MX y datos de relacionado', () => {
      const request: GeneralInfoSection = {
        personClassification: 'B',
        economicActivity: 'ACT-02',
        maritalStatus: '2',
        marriageType: '',
        sector: 'TECH',
        actinverEmployee: false,
        employeeNumber: '',
        occupation: 'DEV',
        profession: 'ENGINEER',
        companyName: '',
        jobTitle: '',
        companyPhone: '',
        domicilieType: 'OFICINA',
        country: 'US',
        postalCode: '75001',
        federalEntity: 'TEXAS',
        federalEntityID: '',
        city: 'DALLAS',
        cityID: '',
        municipality: 'DALLAS',
        municipalityID: '',
        colony: 'NORTH',
        street: 'MAIN',
        externalNumber: '1',
        internalNumber: '',
        website: '',
        related: true,
        relationship: '12',
        institutionName: 'BANK US',
        fiel: '',
        fielExpirationDate: '',
        operatesChanges: false,
        banxicoAuthorization: 'NO',
        nonGuaranteedByIPAB: 'SI',
      };

      const contract = {
        id: 1,
        personId: 1,
        addressId: 1,
        workDataId: 1,
        clientId: 1,
        accountRoleId: 1,
        clientStatus: 'ACTIVE',
        contractStatus: 'OPEN',
        openDate: '',
        initialRiskId: 1,
        initialRiskDescription: '',
        modifyRiskId: 1,
        modifyRiskDespcription: '',
        origin: '',
        n4UpdateDate: '',
        isNumbered: false,
        checkProtected: false,
        isOwnPosition: false,
        isSocialPrevision: false,
        authorizationConsultCreditReports: false,
        biometricsAccount: false,
        facialBiometrics: false,
        enrollmentStatus: '',
        asociatedDirector: '',
        directPromote: '',
        financailCenter: '',
        isrPercentage: 0,
        isrMonthlyCommision: 0,
        comissionPercentage: 0,
        isPMSorety: false,
        isBrokerageHouse: false,
        accountManagementId: null,
        externalCustody: false,
        custody: '',
        custodyIndeval: '',
        financialCenterDelivery: '',
        contractManagement: '',
        gestionType: '',
        vip: false,
        strategyTypes: [],
        equityStrategies: [],
        isEquity: false,
        generalInformationId: null,
        operationReason: '',
        otherReasons: '',
        operationConfiramtionMedia: '',
        documents: false,
        transfers: false,
        accountDeposit: false,
        other: false,
        otherPreferedProduct: '',
        associateDirectorId: null,
        asociatedDirectorStatus: '',
        asociatedDirectorFolio: '',
        asociatedDirectorNumber: 0,
        asociatedDirectorName: '',
        geolocationId: null,
        consentGeolocalization: false,
        date: '',
        time: '',
        latitude: '',
        longitude: '',
        incapacity: false,
        incapacityLetter: false,
        dateOfDefunction: '',
      } as GeneralInfoContract;

      const result = generalInfoToCheckpointMant(request, contract, { executors: [], executorsTable: [], showExecutors: false });

      expect(result.federalEntity).toBe('TEXAS');
      expect(result.city).toBe('DALLAS');
      expect(result.municipality).toBe('DALLAS');
      expect(result.relationship).toBe('12');
      expect(result.institutionName).toBe('BANK US');
      expect(result.fielExpirationDate).toBe('');
    });
  });

  describe('checkpointMantToGeneralInfo', () => {
    it('debe reconstruir clientSection y contractSection para MX', async () => {
      const request: any = {
        personClassification: 'A',
        economicActivity: 'ACT',
        maritalStatus: '1',
        marriageType: 'SOC',
        sector: 'FIN',
        actinverEmployee: true,
        employeeNumber: 'EMP01',
        occupation: 'ANALISTA',
        profession: 'CONTADOR',
        companyName: 'EMPRESA',
        jobTitle: 'PUESTO',
        companyPhone: '555',
        country: 'MX',
        street: 'CALLE',
        externalNumber: '1',
        internalNumber: '2',
        postalCode: '01000',
        federalEntity: '09',
        city: '001',
        municipality: '010',
        neighborhood: 'ROMA',
        website: 'https://test.com',
        related: true,
        relationship: '5',
        institutionName: 'INST',
        fiel: 'FIEL',
        fielExpirationDate: '15/05/2026',
        banxicoAuthorization: 'SI',
        nonGuaranteedByIPAB: 'NO',
        acting: true,
        hasSupplier: true,
        operatesChanges: true,
        contractData: {
          id: 10,
          customerStatus: 'ACTIVE',
          applicationStatus: 'OPEN',
          openingDate: '2024-01-01',
          initialRiskScore: 1,
          initialRiskDescription: 'LOW',
          modifiedRiskScore: 2,
          modifiedRiskDescription: 'MED',
          origin: 'WEB',
          upgradeDateN4: '2024-02-01',
          numbered: true,
          checkProtection: true,
          properPosition: false,
          socialSecurity: true,
          authorizationConsultCreditReports: true,
          biometricsAccount: true,
          facialBiometrics: false,
          codigoSwiftBic: 'BIC123',
          mensajesMt940: true,
          enrollmentStatus: 'ENROLLED',
          associateDirector: 'DIR',
          directPromoter: 'PROM',
          financialCenter: 'CENTER',
          withholdingTax: '10',
          creditSuisseCommission: '2.5',
          commissionPercentage: '1.5',
          legalEntityIGuarantor: false,
          brokerageHouse: true,
        },
        accountManagement: {
          id: 20,
          externalCustody: true,
          custody: 'CUST',
          indevalAccount: 'IND',
          financialCenterDelivery: 'DEL',
          contractManagement: 'MAN',
          managementType: 'TYPE',
          vip: true,
          equityStrategies: ['EQ1'],
        },
        generalInformation: {
          id: 30,
          reasonOperations: 'INV',
          otherReasonOperations: 'OTH',
          confirmationAuthorized: 'EMAIL',
          referringProduct: {
            documents: true,
            transfers: false,
            depositInAccount: true,
            other: false,
            SpecifyPreferredProduct: 'PROD',
          },
        },
        associateDirector: {
          id: 40,
          directorStatus: 'ACTIVO',
          associateDirectorFolio: 'FOLIO',
          advisorNumber: 123,
          name: 'Director Name',
        },
        geolocation: {
          id: 50,
          geolocationConsent: true,
          date: '2024-03-01',
          hour: '10:00',
          latitude: '19.0',
          longitude: '-99.0',
        },
        otherData: {
          incapacity: false,
          disabilityJustification: false,
          dateOfDeath: '',
        },
        personId: 1,
        addressId: 2,
        workDataId: 3,
        clientId: 4,
        accountRoleId: 5,
        isEquity: true,
        codigoSwiftBic: 'BIC123',
        mensajesMt940: true,
      };

      const result = await checkpointMantToGeneralInfo(request, [], [], []);

      expect(result.executorSection).toBeNull();
      expect(result.contractSection).toEqual(jasmine.objectContaining({
        id: 10,
        clientStatus: 'ACTIVE',
        contractStatus: 'OPEN',
        isrPercentage: 10,
        isrMonthlyCommision: 2.5,
        comissionPercentage: 1.5,
        codigoSwiftBic: 'BIC123',
        mensajesMt940: true,
        strategyTypes: ['EQ1'],
        equityStrategies: ['EQ1'],
        personId: 1,
        addressId: 2,
        workDataId: 3,
        clientId: 4,
        accountRoleId: 5,
      }));
      expect(result.clientSection).toEqual(jasmine.objectContaining({
        country: 'MX',
        federalEntityID: '09',
        cityID: '001',
        municipalityID: '010',
        federalEntity: '',
        city: '',
        municipality: '',
        domicilieType: request.addressType,
        colony: 'ROMA',
        codigoSwiftBic: 'BIC123',
        mensajesMt940: true,
      }));
    });

    it('debe reconstruir direccion textual para pais extranjero', async () => {
      const request: any = {
        personClassification: 'B',
        economicActivity: 'ACT',
        maritalStatus: '2',
        marriageType: '',
        sector: 'TECH',
        actinverEmployee: false,
        employeeNumber: '',
        occupation: 'DEV',
        profession: 'ENG',
        companyName: '',
        jobTitle: '',
        companyPhone: '',
        country: 'US',
        street: 'MAIN',
        externalNumber: '10',
        internalNumber: '',
        postalCode: '75001',
        federalEntity: 'TEXAS',
        city: 'DALLAS',
        municipality: 'DALLAS COUNTY',
        neighborhood: 'NORTH',
        website: '',
        related: false,
        relationship: '',
        institutionName: '',
        fiel: '',
        fielExpirationDate: '',
        banxicoAuthorization: 'NO',
        nonGuaranteedByIPAB: 'SI',
        acting: false,
        hasSupplier: false,
        operatesChanges: false,
        contractData: {
          id: 1,
          customerStatus: '',
          applicationStatus: '',
          openingDate: '',
          initialRiskScore: 0,
          initialRiskDescription: '',
          modifiedRiskScore: 0,
          modifiedRiskDescription: '',
          origin: '',
          upgradeDateN4: '',
          numbered: false,
          checkProtection: false,
          properPosition: false,
          socialSecurity: false,
          authorizationConsultCreditReports: false,
          biometricsAccount: false,
          facialBiometrics: false,
          codigoSwiftBic: '',
          mensajesMt940: false,
          enrollmentStatus: '',
          associateDirector: '',
          directPromoter: '',
          financialCenter: '',
          withholdingTax: '0',
          creditSuisseCommission: '0',
          commissionPercentage: '0',
          legalEntityIGuarantor: false,
          brokerageHouse: false,
        },
        accountManagement: { equityStrategies: [] },
        generalInformation: { referringProduct: {} },
      };

      const result = await checkpointMantToGeneralInfo(request, [], [], []);

      expect(result.clientSection.country).toBe('US');
      expect(result.clientSection.federalEntity).toBe('TEXAS');
      expect(result.clientSection.city).toBe('DALLAS');
      expect(result.clientSection.municipality).toBe('DALLAS COUNTY');
      expect(result.clientSection.federalEntityID).toBe('');
      expect(result.clientSection.cityID).toBe('');
      expect(result.clientSection.municipalityID).toBe('');
    });
  });
});
