export const ROLES = {
  ROL_SUBGERENTE_ADMINISTRATIVO: "ROL_SUBGERENTE_ADMINISTRATIVO",
  ROL_ANALISTA_DE_CONTRATOS: "ROL_ANALISTA_DE_CONTRATOS",
  SPINE_GESTOR_SUP: "SPINE_GESTOR_SUP",
  SPINE_GESTOR_OP: "SPINE_GESTOR_OP",
  ROL_CAT_SEDI: "ROL_CAT_SEDI",
  ROL_CAT_VIDEOLLAMADAS: "ROL_CAT_VIDEOLLAMADAS",
  ROL_GEN_SOL_CONSULTA: "ROL_GEN_SOL_CONSULTA",
  ROL_CRÉDITO_PF_PM: "ROL_CRÉDITO_PF_PM",
};