import { Tabs } from '../models/tabs';

export const TABS_PF: Array<Tabs> = [
  {
    label: 'Datos Iniciales de Cliente',
    path: 'customer-info',
    step: 1,
    disabled: false,
    hide: false,
  },
  {
    label: 'Datos Generales',
    path: 'general-info',
    step: 2,
    disabled: true,
    hide: false,
  },
  {
    label: 'Identificación y Datos de Contacto',
    path: 'contact-info',
    step: 3,
    disabled: true,
    hide: false,
  },
  {
    label: 'Datos de Cónyuge',
    path: 'spouse',
    step: 19,
    disabled: true,
    hide: true,
  },
  {
    label: 'Información PPE',
    path: 'ppe-info',
    step: 4,
    disabled: true,
    hide: false,
  },
  {
    label: 'Domicilio',
    path: 'address',
    step: 5,
    disabled: true,
    hide: false,
  },
  {
    label: 'Firma',
    path: 'sign',
    step: 6,
    disabled: true,
    hide: false,
  },
  {
    label: 'Beneficiarios',
    path: 'beneficiaries',
    step: 7,
    disabled: true,
    hide: false,
  },
  {
    label: 'Persona Autorizada',
    path: 'authorized-person',
    step: 8,
    disabled: true,
    hide: false,
  },
  {
    label: 'Cuentas Bancarias',
    path: 'bank-account',
    step: 9,
    disabled: true,
    hide: false,
  },
  {
    label: 'Perfil de Inversión Transaccional',
    path: 'transactional-investment-profile',
    step: 10,
    disabled: true,
    hide: false,
  },
  {
    label: 'Auto-Certificación y Datos Fiscales',
    path: 'tax-info',
    step: 11,
    disabled: true,
    hide: false,
  },
  {
    label: 'Entrevista Personal',
    path: 'interview',
    step: 12,
    disabled: true,
    hide: false,
  },
  {
    label: 'Aviso de Privacidad',
    path: 'privacy-notice',
    step: 13,
    disabled: true,
    hide: false,
  },
  {
    label: 'Propietario Real',
    path: 'real-owner',
    step: 14,
    disabled: false,
    hide: true,
  },
  {
    label: 'Proveedor de Recursos',
    path: 'resource-provider',
    step: 15,
    disabled: false,
    hide: true,
  },
  {
    label: 'Opera cambios',
    path: 'operate-changes',
    step: 16,
    disabled: false,
    hide: true,
  },
  {
    label: 'Cuestionario PLD',
    path: 'pld-quiz',
    step: 17,
    disabled: false,
    hide: true,
  },
  {
    label: 'Perfil Fiscal',
    path: 'tax-profile',
    step: 18,
    disabled: false,
    hide: true, //TODO aqui los cambios para cuando entre a mantenimineto
  },
  {
    label: 'Información Adicional',
    path: 'additional-info',
    step: 19,
    disabled: false,
    hide: true,
  },
  {
    label: 'Datos Crediticios',
    path: 'credit-data',
    step: 20,
    disabled: false,
    hide: true,
  },
  {
    label: 'Actiweb',
    path: 'actiweb',
    step: 21,
    disabled: false,
    hide: true,
  },
];

export const TABS_PM: Array<Tabs> = [
  {
    label: 'Identificación de Cliente',
    path: 'customer-info-pm',
    step: 1,
    disabled: false,
    hide: false,
  },
  {
    label: 'Consejo Administrativo',
    path: 'directorate',
    step: 2,
    disabled: false,
    hide: false,
  },
  {
    label: 'Datos Generales',
    path: 'general-info-pm',
    step: 3,
    disabled: false,
    hide: false,
  },
  {
    label: 'Perfil SPID',
    path: 'spid-profile-pm',
    step: 4,
    disabled: false,
    hide: false,
  },
  {
    label: 'Organigrama',
    path: 'organization-chart',
    step: 4,
    disabled: false,
    hide: false,
  },
  {
    label: 'Datos de Contacto',
    path: 'contact-info-pm',
    step: 5,
    disabled: false,
    hide: false,
  },
  {
    label: 'Estatus de la Entidad',
    path: 'entity-status',
    step: 6,
    disabled: false,
    hide: false,
  },
  {
    label: 'Domicilio',
    path: 'address-pm',
    step: 7,
    disabled: false,
    hide: false,
  },
  {
    label: 'Beneficiarios',
    path: 'beneficiaries-pm',
    step: 8,
    disabled: false,
    hide: false,
  },
  {
    label: 'Persona Autorizada',
    path: 'authorized-person',
    step: 8,
    disabled: false,
    hide: false,
  },
  {
    label: 'Cuentas Bancarias',
    path: 'bank-account',
    step: 9,
    disabled: false,
    hide: false,
  },
  {
    label: 'Administrador que Ejerce el Control',
    path: 'administrator-exercising-pf-control',
    step: 9,
    disabled: false,
    hide: false,
  },
  {
    label: 'Proveedor de Recursos',
    path: 'resource-provider-pm',
    step: 10,
    disabled: false,
    hide: false,
  },
  {
    label: 'Propietario Real',
    path: 'real-owner-pm',
    step: 11,
    disabled: false,
    hide: false,
  },
  {
    label: 'Perfil de Inversión Transaccional',
    path: 'transactional-investment-profile-pm',
    step: 12,
    disabled: false,
    hide: false,
  },
  {
    label: 'Firma',
    path: 'sign',
    step: 13,
    disabled: false,
    hide: false,
  },
  {
    label: 'Cuestionario PLD',
    path: 'pld-quiz-pm',
    step: 14,
    disabled: false,
    hide: true,
  },
  {
    label: 'Opera cambios',
    path: 'operate-changes-pm',
    step: 16,
    disabled: false,
    hide: true,
  },
];

export const TABS_TRUST: Array<Tabs> = [
  {
    label: 'Crear Fideicomiso Interno',
    path: 'intern-trust',
    step: 1,
    disabled: false,
    hide: false,
  },
  {
    label: 'Solicitudes Fideicomiso',
    path: 'trust-request',
    step: 2,
    disabled: false,
    hide: false,
  },
];
